[colors.bright]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.normal]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[cursor]
style = "Underline"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.offset]
x = -1
y = 1

[window.padding]
x = 6
y = 6
