#!/bin/bash

rm -rf README.md .git
mv terminator/config $HOME/.config/terminator/config
mkdir $HOME/.i3
mv .i3/config $HOME/.i3/config
mv .i3/touchpad.sh $HOME/.i3/touchpad.sh
mv * $HOME
cd ..
rm -rf dotfiles/
