#!/bin/sh

OUTPUT="$(acpi)"
REMAINING="$(awk '{print $5}' <<< $OUTPUT)"
PERCENTAGE="$(awk -F', ' '{print $2}' <<< $OUTPUT)"

echo "$REMAINING [$PERCENTAGE]"
echo
(( $(sed 's/%//' <<< "$PERCENTAGE") < 10 )) && echo \#FF0000 || exit 0
