#!/bin/sh

OUTPUT="$(acpi)"
REMAINING="$(printf '%s' "$OUTPUT" | awk '{print $5}')"
PERCENTAGE="$(printf '%s' "$OUTPUT" | awk -F', ' '{print $2}')"

echo "$REMAINING [$PERCENTAGE]"
echo

COLOR=$(( $(printf '%s' "$PERCENTAGE" | sed 's/%//') < 10 ))
[ ! "$COLOR" ] && echo \#FF0000 || exit 0
