#!/bin/sh

case $BLOCK_BUTTON in
    2) xset dpms force off ;;
    4) light -A 2 ;;
    5) light -U 5 ;;
esac

if [ -e "$BLOCK_INSTANCE" ] ; then
    VALUE="$("$BLOCK_INSTANCE")"
    echo "☀ [${VALUE%.*}%]"
fi
