#!/bin/sh

MENU=$(printf "dark\nlock\nhalt\nwarm\nkill" | rofi -dmenu)

[ -z "$MENU" ] && exit 0

case "$MENU" in
    dark)
        xset dpms force off ;;
    lock)
        "$HOME/dotfiles/.i3/lock" && sleep 1 ;;
    halt)
        "$HOME/dotfiles/.i3/lock" && systemctl suspend ;;
    warm)
        systemctl reboot ;;
    kill)
        systemctl poweroff ;;
esac
