#!/bin/sh

ICAO="${BLOCK_INSTANCE:-NWWW}"
SITE="http://tgftp.nws.noaa.gov/data/observations/metar/decoded/$ICAO.TXT"
NOAA="$(curl -s "$SITE")"
PRETTY="http://weather.noaa.gov/weather/current/$ICAO.html"

TEMPERATURE="$(echo "$NOAA" | awk -F"[()]" '/Temp/ {print $2}')"
CONDITION="$(echo "$NOAA" | awk -F": " '/Sky/ {print $2}')"
WEATHER="$(echo "$NOAA" | awk -F": " '/Weather/ {print $2}')"

if [ -n "$WEATHER" ] && [ -n "$CONDITION" ] && [ -n "$TEMPERATURE" ] ; then
    echo "$CONDITION, $WEATHER [$TEMPERATURE]"
elif [ -n "$CONDITION" ] && [ -n "$TEMPERATURE" ] ; then
    echo "$CONDITION [$TEMPERATURE]"
elif [ -z "$CONDITION" ] && [ -n "$TEMPERATURE" ]; then
    echo "$TEMPERATURE"
fi

[ -n "$BLOCK_BUTTON" ] && chromium "$PRETTY" &
