#!/bin/sh

ICAO="${BLOCK_INSTANCE:-NWWW}"
SITE="http://weather.noaa.gov/weather/current/$ICAO.html"
NOAA="$(curl -s "$SITE")"

CONDITION="$(printf '%s' "$NOAA" | awk -F">  " 'NR==150 {print $2}')"
TEMPERATURE="$(printf '%s' "$NOAA" | sed -n '/Temp/{n;n;p;q}' | \
               awk -F "[()]" '{print $2}')"

[ -n "$CONDITION" ] && [ -n "$TEMPERATURE" ] && echo "$CONDITION [$TEMPERATURE]"
[ "$BLOCK_BUTTON" -eq 1 ] && chromium "$SITE" &
