#!/bin/sh

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

[ "$(cat /sys/class/net/"$INTERFACE"/operstate)" = 'down' ] && exit

QUALITY=$(grep "$INTERFACE" /proc/net/wireless \
            | awk '{print int($3 * 100 / 70)}')

# iwgetid needs wireless_tools
[ -n "$QUALITY" ] && echo "$(iwgetid -r) [$QUALITY%]"
