#!/bin/bash

# various config files
ln -fs $HOME/.files/.{aliases,bash_profile,gitconfig,tmux.conf,Xresources} $HOME
ln -fs $HOME/.files/.{asound,bash,input,vim,xinit}rc $HOME
ln -fP $HOME/.files/conf/redshift.conf $HOME/.config
ln -fP $HOME/.files/conf/.makepkg.conf $HOME
sudo mkdir /etc/systemd/journald.conf.d
sudo ln -fs $HOME/.files/conf/20-journal-rules.conf /etc/systemd/journald.conf.d

# keyboard settings
localectl --no-convert set-keymap us-acentos
localectl --no-convert set-x11-keymap us pc105 intl

# vim stuff
aur vim-{badwolf,gitgutter,lightline}-git
