#!/bin/sh

if [ "$(pgrep -c sway)" -gt 0 ] ; then
  MANAGER="swaylock"
  SCREENCAP="swaygrab"
else
  MANAGER="i3lock"
  SCREENCAP="scrot"
fi

TMPBG="/tmp/screen.png"
"$SCREENCAP" "$TMPBG"
convert "$TMPBG" -scale 50% -blur 0x5 -scale 200% "$TMPBG"
"$MANAGER" -u -i "$TMPBG"
