#!/bin/sh

MENU=$(printf "dark\nlock\nhalt\nwarm\nkill" \
        | rofi -location 5 -columns 1 -lines 5 -width 6 -regex -dmenu)

[ -z "$MENU" ] && exit 0

case "$MENU" in
    dark)
        xset dpms force off ;;
    lock)
        "$HOME/.files/scripts/lock" && sleep 1 ;;
    halt)
        "$HOME/.files/scripts/lock" && systemctl suspend ;;
    warm)
        systemctl reboot ;;
    kill)
        systemctl poweroff ;;
esac
